config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end

  resources :projects do
    member do
      get :finish
    end

    member do
      get :finishtask
    end

    member do
      get :reversetask
    end

    member do
      get :finishtasks
    end

    member do
      get :return
    end

    member do
      post :newtask
    end 

    member do
      post :newtasklist
    end

    member do
      post :updatetask
    end

    member do
      post :updatetasklist
    end
  end

  resources :tasklists do
    put :sort
  end

  resources :tasks do
    put :sort
  end

  root "projects#index"
  resources :tasks, only: [:index,:new,:create,:edit,:update]
end

app/views/shared/_header.html.haml
.header
  = link_to root_path, class:"title-link" do
    .header__title
      .header__title--icon
        = icon('fas', 'leaf')
      .header__title--title
        PlanDo
  .header__user
    -if user_signed_in?
      .header__user--project
        =link_to "プロジェクト一覧",projects_path, class: 'user-project'
      .header__user--nickname
        =link_to "#{current_user.nickname}様",edit_user_registration_path, class: 'user-name'
      .header__user--logout
        =link_to "ログアウト",destroy_user_session_path, method: :delete, class: 'user-btn'
    -else
      .header__user--sign-up
        =link_to "新規登録",new_user_registration_path, class: 'user-btn'
      .header__user--login
        =link_to "ログイン",new_user_session_path, class: 'user-btn'