config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end

  resources :projects do
    member do
      get :finish
    end

    member do
      get :finishtask
    end

    member do
      get :reversetask
    end

    member do
      get :finishtasks
    end

    member do
      get :return
    end

    member do
      post :newtask
    end 

    member do
      post :newtasklist
    end

    member do
      post :updatetask
    end

    member do
      post :updatetasklist
    end
  end

  resources :tasklists do
    put :sort
  end

  resources :tasks do
    put :sort
  end

  root "projects#index"
  resources :tasks, only: [:index,:new,:create,:edit,:update]
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  has_many :tasklists
  belongs_to :user
  validates :name, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :correct_user,   only: [:show, :edit, :update]
  def index
    if user_signed_in?
      @projects = Project.where(user_id: current_user.id)
    end
  end

  def new
    @project = Project.new
  end

  def create
    # Project.create(project_params)
    # redirect_to root_path
    @project = Project.new(project_params)
    if @project.save
      redirect_to root_path
    else
      render "new"
    end
  end

  def show
    @project = Project.find(params[:id])
    @tasklists = Tasklist.where(project_id: @project.id).rank(:row_order)
    @task = Task.new
    @tasklist = Tasklist.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to project_path(params[:id])
    else
      render 'projects/edit'
    end
  end

  def newtasklist
    Tasklist.create(tasklist_new_params)
    redirect_to project_path(params[:id])
  end

  def newtask
    Task.create(task_new_params)
    redirect_to project_path(params[:id])
  end

  def updatetask
    task = Task.find(params[:task_id])
    task.update(task_edit_params)
    redirect_to project_path(params[:id])
  end

  def updatetasklist
    tasklist = Tasklist.find(params[:tasklist_id])
    tasklist.update(tasklist_edit_params)
    redirect_to project_path(params[:id])
  end

  def finish
    project = Project.find(params[:id])
    project.update(finish: true)
    redirect_to root_path
  end

  def finishtask
    task = Task.find(params[:task_id])
    task.update(finish: true)
    redirect_to project_path(params[:id])
  end

  def reversetask
    task = Task.find(params[:task_id])
    task.update(finish: false)
    redirect_to project_path(params[:id])
  end

  def finishtasks
    tasks = Task.where(tasklist_id: params[:tasklist_id])
    tasks.each do |t|
      t.update(finish: true)
    end
    redirect_to project_path(params[:id])
  end

  def return
    project = Project.find(params[:id])
    project.update(finish: false)
    redirect_to root_path
  end

  def destroy
    project = Project.find(params[:id])
    project.destroy
    redirect_to root_path
  end

  private
  def project_params
    params.require(:project).permit(:name, :finish_date, :finish, :created_at, :updated_at).merge(user_id: current_user.id)
  end
  
  def task_new_params
    params.require(:task).permit(:text,:project_id,:tasklist_id).merge(user_id: current_user.id)
  end

  def tasklist_new_params
    params.require(:tasklist).permit(:name,:project_id).merge(user_id: current_user.id)
  end

  def task_edit_params
    params.require(:task).permit(:text,:project_id,:tasklist_id,:id,:detail,:finish_date,:color).merge(user_id: current_user.id)
  end

  def tasklist_edit_params
    params.require(:tasklist).permit(:name,:project_id,:id).merge(user_id: current_user.id)
  end

  def correct_user
    @user = User.find(Project.find(params[:id]).user_id)
  unless current_user == @user
    redirect_to(root_path) 
  end
  end
end

app/views/projects/edit.html.haml
.project-new
  .project-edit__text
    = icon('fas', 'edit')
    プロジェクトを編集する
  .project-new__form
    =form_for(@project) do |f|
      = render 'layouts/error_messages', model: f.object
      .project-new__form__name
        プロジェクトの名前を設定
        %br/
        = f.text_field :name,class:"form-name",placeholder: "プロジェクト名"
      .project-new__form__finish
        完了予定日の設定
        %br/
        = f.text_field :finish_date,class:"form-finish datepicker", placeholder: "完了予定日（例：2020/01/01）"
      .project-new__form__btn-form
        = f.submit "プロジェクトを更新する",class:"form-btn"
      .project-new__form__btn-form-destroy
        = link_to "プロジェクトを削除する", project_path(@project.id), method: :delete, class:"form-btn-destroy", data: { confirm: 'このプロジェクトを本当に削除しますか？（削除したプロジェクトは元に戻すことができません）' }

app/views/projects/index.html.haml
= render "shared/header"
-if user_signed_in?
  .main-content
    .main-content__bottom-content
      =link_to new_project_path, class:"new-project-btn" do
        .new-project-form
          = icon('fas', 'plus-circle')
          新規プロジェクトを作成する
      .container
        .menu
          .menu-item.project-active
            進行中(
            = @projects.where(finish: false).length
            )
          .menu-item
            完了済(
            = @projects.where(finish: true).length
            )
        .contents.show
          - @projects.where(finish:false).each do |project|
            = link_to "projects/#{project.id}", class: "projects-link" do
              .content
                = icon('fas', 'arrow-alt-circle-right')
                = project.name
        .contents
          - @projects.where(finish:true).each do |project|
            = link_to "projects/#{project.id}", class: "projects-link" do
              .content-finish
                = icon('fas', 'arrow-alt-circle-right')
                = project.name
-else
  .main-image
    .top-left
      .top-left__image-title
        PlanDo
      .top-left__image-text
        タスク管理をもっとシンプルに。

    .top-right
      =link_to new_user_registration_path do
        .top-right__signup
          新規登録
      =link_to new_user_session_path do
        .top-right__login
          ログイン


-# １、プロジェクトごとにタスクを管理

-# ２、カード形式でタスクを管理

-# ３、直感操作でスムーズなタスク管理

app/views/projects/new.html.haml
.project-new
  .project-new__text
    = icon('fas', 'plus-circle')
    新規プロジェクトを作成する
  .project-new__form
    =form_for(@project) do |f|
      = render 'layouts/error_messages', model: f.object
      .project-new__form__name
        プロジェクトの名前を設定（必須）
        %br/
        = f.text_field :name,class:"form-name",placeholder: "プロジェクト名"
      .project-new__form__finish
        完了予定日の設定（任意）
        %br/
        = f.text_field :finish_date,class:"form-finish datepicker", placeholder: "完了予定日（例：2020/01/01）"
      .project-new__form__btn-form
        = f.submit "プロジェクトを作成する",class:"form-btn"

app/views/projects/show.html.haml
= render "shared/header"

.task-content
  .task-top
    .task-top__left
      .task-top__left__project-name
        = @project.name
        -if @project.finish == true
          %span.project-name-finish
            (完了済)
      -if @project.tasks.present?
        .task-top__left__p-progress
          達成率
          - progress = @project.tasks.where(finish: true).length * 100 / @project.tasks.length
          = "#{progress.to_i}%"
          (
          = "#{@project.tasks.where(finish: true).length} /"
          = @project.tasks.length
          )
      -if @project.finish_date.present?
        .task-top__left__p-date
          -require 'date'
          -today = Date.today
          -future = @project.finish_date
          -remainingDay = future - today
          -if remainingDay <= 7
            完了予定日まであと
            %span.warning
              = remainingDay.to_i
            日（
            = @project.finish_date
            ）
          -else
            完了予定日まであと
            %span.normal
              = remainingDay.to_i
            日（
            = @project.finish_date
            ）
    .task-top__right
      = link_to edit_project_path do
        .task-top__right__edit
          編集
      .task-top__right__finish-task
        完了済のタスク
        %ul.drop-finish-tasklist
          - @project.tasks.each do |task|
            -if task.finish == true
              %li.drop-finish-tasks
                =task.text
                .drop-finish-task-bottom
                  .drop-finish-task-reverse
                    = link_to "元に戻す", reversetask_project_path(task_id:task.id, project_id: task.project_id), class:"task-reverse"
                  .drop-finish-task-delete
                    = link_to "削除する", task_path(id: task.id, project_id: task.project_id), method: :delete, class:"task-delete", data: { confirm: 'このタスクを削除しますか？' }
      -if @project.finish == false
        = link_to finish_project_path(params[:id]), data: { confirm: 'このプロジェクトを完了済に移動しますか？' }  do
          .task-top__right__finish
            完了済に移動
      -else
        = link_to return_project_path(params[:id]), data: { confirm: 'このプロジェクトを進行中に移動しますか？' } do
          .task-top__right__finish
            進行中に移動
  .task-bottom
    %ul.sortable-tasklist.sortable-tasklist-parent
      -if @tasklists.present?
        -@tasklists.each do |tasklist|
          %li.sortable-tasklist-child{ "data-update_url": "#{tasklist_sort_path(tasklist.id)}","data-list-id": "#{tasklist.id}","data-finish": "0"}
            .task-bottom__task-list
              .tasklist-title-box
                .task-bottom__task-list--task-title.js-modal-open-edittasklist{data: {id:tasklist.id}}
                  = tasklist.name
                .task-finish-icon
                  = link_to finishtasks_project_path(tasklist_id: tasklist.id), class:"task-finish-icon-link", data: { confirm: 'このタスクリスト上にある全てのタスクを完了済にしますか？' }  do
                    = icon('fas', 'check-square')
              
              .modal.js-modal-edittasklist{data: {id: tasklist.id}}
                .modal__bg.js-modal-close-edittasklist
                .modal__content-tasklist-edit
                  .js-modal-close-edittasklist
                    = icon('fas', 'times')
                  .new-task__form
                    =form_for(tasklist,url: updatetasklist_project_path(tasklist_id: tasklist.id),method: :post, html:{class:'send-edittasklist-form'}) do |f|
                      = f.hidden_field :project_id, value: @project.id
                      .new-task__form__name
                        = f.text_field :name,class:"form-name",placeholder: "タスクリストの名前を入力"
                      .tasklistedit-btns
                        .new-task__form__btn-form
                          = f.submit "タスクリストを更新する",class:"form-btn-tasklistedit"
                        = link_to tasklist_path(id: tasklist.id, project_id: tasklist.project_id), method: :delete,class:'form-btn-destroy-tasklist-link' do
                          .form-btn-destroy-tasklist
                            タスクリストを削除する

              .modal.js-modal{data: {id: tasklist.id}}
                .modal__bg.js-modal-close
                .modal__content
                  .js-modal-close
                    = icon('fas', 'times')
                  .new-task__form
                    =form_for(@task,url: newtask_project_path,method: :post, html:{tasklist_id: tasklist.id, class:'send-task-form'}) do |f|
                      = f.hidden_field :project_id, value: @project.id
                      = f.hidden_field :tasklist_id, value: tasklist.id
                      .new-task__form__name
                        = f.text_field :text,class:"form-name",placeholder: "タスクを入力"
                      .new-task__form__btn-form
                        = f.submit "タスクを作成する",class:"form-btn"

              .task-bottom__task-list--tasks
                %ul.sortable.sortable-task-parent
                  -if tasklist.tasks.present?
                    -tasklist.tasks.rank(:row_order).each do |task|
                      -if task.finish == false
                        %li.sortable-task-child{ "data-update_url": "#{task_sort_path(task.id)}"}
                          .task-bottom__task-list--tasks--task.js-modal-open-edittask{data: {id: task.id, row: task.id},style: 'border-left: solid 10px' + task.color + ';'}
                            = task.text
                            -# -if task.finish_date.present?
                            -#   .task-finish-date
                            -#     = icon('fas', 'clock')
                            -#     = task.finish_date
                          .modal.js-modal-edittask{data: {id:task.id}}
                            .modal__bg.js-modal-close-edittask
                            .modal__content-edit
                              .js-modal-close-edittask
                                = icon('fas', 'times')
                              .new-task__form
                                =form_for(task,url: updatetask_project_path(task_id: task.id),method: :post, html:{class:'send-edittask-form'}) do |f|
                                  = f.hidden_field :project_id, value: @project.id
                                  .new-task__form__name
                                    = f.text_field :text,class:"form-name",placeholder: "タスクを入力"
                                  .new-task__form__detail
                                    .taskform-detail-text
                                      = icon('fas', 'bars')
                                      詳細情報
                                    = f.text_area :detail,class:"form-detail",placeholder: "詳細情報を入力"
                                  -# .new-task__form__finish-date
                                  -#   .taskform-finish-text
                                  -#     = icon('fas', 'clock')
                                  -#     完了予定日
                                  -#   = f.text_field :finish_date,class:"form-date",placeholder: "完了予定日を入力（例：2020/01/01）", "data-row": task.id
                                  .new-task__form__color
                                    .taskform-color-text
                                      = icon('fas', 'palette')
                                      タスクカラーの変更
                                    = f.color_field :color,class:"form-color"
                                  .new-task__form__btn-form-taskedit
                                    = f.submit "タスクを更新する",class:"form-btn-taskedit"
                                  .taskedit-btns
                                    = link_to finishtask_project_path(task_id: task.id),class:"form-btn-finish-task-link", data: { confirm: 'このタスクを完了済にしますか？' }  do
                                      .task-finish
                                        タスクを完了済にする
                                    = link_to task_path(id: task.id, project_id: task.project_id), method: :delete, class:"form-btn-destroy-task-link", data: { confirm: 'このタスクを削除しますか？' }  do
                                      .form-btn-destroy-task
                                        タスクを削除する

              .new-task-frame.js-modal-open{data: {id: tasklist.id}}
                .new-task
                  = icon('fas', 'plus-circle')
                  新しいタスクを作成

    .task-bottom__new-list.js-modal-open-tasklist
      = icon('fas', 'plus-circle')
      新しいリストを作成

.modal.js-modal-tasklist
  .modal__bg.js-modal-close-tasklist
  .modal__content
    .js-modal-close-tasklist
      = icon('fas', 'times')
    .new-task__form
      =form_for(@tasklist,url: newtasklist_project_path,method: :post,html:{class:'send-tasklist-form'}) do |f|
        = f.hidden_field :project_id, value: @project.id
        .new-task__form__name
          = f.text_field :name,class:"form-name",placeholder: "タスクリストの名前を入力"
        .new-task__form__btn-form
          = f.submit "タスクリストを作成する",class:"form-btn-tasklist"